version: "3.9"

services:

  streamlit_app:
    env_file:
      - .env
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    environment:
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
    volumes:
      - ./hotel_price_absorber_src:/app/hotel_price_absorber_src
      - ./database:/database
    container_name: hotel-prices
    ports:
      - "8501:8501"  # Keep for local access
    restart: unless-stopped
    networks:
      - hotel_prices_network

  hotel_prices_redis:
    container_name: hotel_prices_redis
    image: redis
    restart: always
    volumes:
      - ./redis_data:/data
      - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --loglevel warning
    ports:
      - "16390:16390"
    environment:
    - REDIS_MAXMEMORY=2048mb
    networks:
      - hotel_prices_network

  worker:
    build: .
    env_file:
      - .env
    command: rq worker
    volumes:
    - ./scripts:/home/seluser/scripts
    - ./database:/home/seluser/database
    ports:
        - "4444:4444"
        - "7900:7900"
    shm_size: 4g
    environment:
      - DB_PATH=/home/seluser/database
      - REDIS_URL=redis://hotel_prices_redis:16390
    depends_on:
      - hotel_prices_redis
    networks:
      - hotel_prices_network

networks:
  hotel_prices_network:
    driver: bridge