
version: "3.9"

services:

  influxdb:
    image: influxdb:2.7
    container_name: price-monitor-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    restart: unless-stopped
    networks:
      - hotel_prices_network
  streamlit_front:
    build:
      context: ./streamlit_front
      dockerfile: Dockerfile
    container_name: streamlit-front-app
    ports:
      - "8501:8501"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - hotel_prices_network

  scraper:
    build: .
    container_name: scraper_worker
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: celery -A celery_app worker --loglevel=info

  beat:
    build: .
    container_name: scheduler_beat
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: celery -A celery_app beat --loglevel=info
  hotel_prices_redis:
    container_name: hotel_prices_redis
    image: redis
    restart: always
    # Persistent storage
    volumes:
      - ./redis_data:/data
      - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --loglevel warning
    ports:
      - "16380:16380"
    environment:
    - REDIS_MAXMEMORY=2048mb # Limit Redis memory usage to 1024mb
    networks:
      - hotel_prices_network

networks:
  hotel_prices_network:
    driver: bridge